### ISSUE TITLE
last.fm integration? (also woo issue 100)

### ISSUE THREAD

**Issue by lxjv** [neatnik/omg.lol#100]
idk if this is possible but it would be pretty cool

so you could show, lets sayyyy

someones last 3 played songs? and its all customizable

**Comment by theKAKAN** [comment]
Oh, if you're going to support last.fm, maybe add [Listen Brainz](https://listenbrainz.org/) as well ?
That might be a bit more difficult, since that one can be self-hosted...

**Comment by LakerJV** [comment]
yeah, also thinking support for https://libre.fm and [krateng/maloja](https://github.com/krateng/maloja)

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605127850759
