### ISSUE TITLE
Add Lobsters icon

### ISSUE THREAD

**Issue by winterqt** [neatnik/omg.lol#142]
[Lobsters](https://lobste.rs) is a computing-focused community centered around link aggregation and discussion.

There's a copy of the icon in various formats [in the GitHub repository](https://github.com/lobsters/lobsters/tree/master/public).

**Comment by newbold** [comment]
All set!

<img width="169" alt="Screen Shot 2021-11-01 at 9 02 57 PM" src="https://user-images.githubusercontent.com/986721/139770238-b3fba71e-c901-4754-a6b4-6ab16fc79549.png">
