### ISSUE TITLE
Adjust renewal reminder process (1 reminder email to 3)

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#144]
Feedback from customers has indicated that one renewal reminder message isn't enough. My original intent here was to not pester people, but it turns out that it bothers people more when their address expires and someone else scoops it up. 🙁

- [x] Update renewal process to support multiple timed reminders
- [x] Contact 13 customers with upcoming expired addresses who've received one reminder message (that specifically said it would be the only message they'd receive, so it might be a little weird to reach out again, but they deserve to benefit from the updated process. Maybe? I don't know. Can't hurt I guess.)

**Comment by newbold** [comment]
Also, I'm thinking this renewal reminder schedule:

- Initial email 30 days prior to expiration
- Reminder email 14 days prior to expiration
- Final "omg this is it take action now or else" email 24 hours prior to expiration

**Comment by fm** [comment]
Or, maybe even let users customize the schedule, like Hover does

<img width="574" alt="Screen Shot 2022-03-05 at 6 31 57 PM" src="https://user-images.githubusercontent.com/3654256/156903136-9af06f24-7f53-4894-85b1-7a76d6f83bf1.png">

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605135447292

**Comment by newbold** [comment]
Landed on 60 days, 30 days, and 14 days for now — but will consider customizable notifications!
