### ISSUE TITLE
Add an icon for Literal

### ISSUE THREAD

**Issue by heyTimApple** [neatnik/omg.lol#149]
If possible it would be great to have an icon for literal.club for the profile.. this is mine https://literal.club/timapple

Thanks

![image](https://user-images.githubusercontent.com/50109194/140661538-95dc2a4c-68b3-4b37-9538-5d6362801ccf.png)

**Comment by newbold** [comment]
Hey Tim! Thanks for sharing this — while there already was an icon for Literal in place, there was a small glitch in the SVG that prevented it from rendering correctly. The file has been updated and the icon should now appear on your profile page. Sorry about that, and thanks again for pointing it out!

**Comment by lakerjv** [comment]
![image](https://user-images.githubusercontent.com/63261955/140661682-72291dcc-b4b8-4469-a500-3daa88fd56df.png)
works great on my profile!

**Comment by heyTimApple** [comment]
Thanks!
