### ISSUE TITLE
Fix support for Mastodon

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#15]

**Comment by cygnoir** [comment]
Adding my Mastodon link to my profile breaks the link. [The profile items page](https://home.omg.lol/info/profile-items) says to use `mastodon://` but doing that creates a link like `https://mastodon//@cygnoir@social.lol`

**Comment by newbold** [comment]
Thanks, @cygnoir, for letting me know about the outdated documentation. I’ve just spruced it up a bit! Sorry for the confusion.
