### ISSUE TITLE
Allow gift code redemption for existing addresses (adding time)

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#159]

**Comment by ChxseH** [comment]
IMHO if you extend someone else's time they shouldn't have to do anything, it should just be automatic as I can't see any downsides for "rejecting" an extension paid by someone else

**Comment by fm** [comment]
I've always loved that Hover lets you [renew domains](https://help.hover.com/hc/en-us/articles/217282397-Using-Hover-s-No-Hassle-renewal-feature) for others

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605137090975

**Comment by Vukkyy** [comment]
This is shipped, right?

![Image](https://user-images.githubusercontent.com/46850780/215291181-30b6b851-cc30-40b4-b1e9-cf4450b9b80a.png)

**Comment by newbold** [comment]
Yeah, thanks!
