### ISSUE TITLE
Profile Icon suggestions

### ISSUE THREAD

**Issue by ThijsNameIsTaken** [neatnik/omg.lol#16]
Some profile icons that can be added.

Discord: 2 formats, a link format (like https://discord.gg/stz2xUMVa8) for servers, and maybe a discord://TagHere#0001 or discord:TagHere#0001 format for names.
Patreon: https://patreon.com/link
Spotify: https://open.spotify.com/user/11137004079

I have some more but I currently forgot what it was, oof. Will comment if I have any more that I forgot.

**Comment by newbold** [comment]
These are all set. For Discord Servers and Spotify (or anything that doesn't have the desired display name in the URL), it's best to use Markdown-formatted links, like this:

* [Neatnik Discord](https://discord.gg/3SdFYb66SA)
* [neatnik](https://open.spotify.com/user/kfxi7920pzfg0atzb79e6mi0b)

This will ensure that the right icons are displayed, as well.
