### ISSUE TITLE
Bug: Appending /wut to PURLs doesn't load preview 

### ISSUE THREAD

**Issue by dcchambers** [neatnik/omg.lol#160]
For example:

https://dakota.omg.lol/example --> https://example.com/
https://dakota.url.lol/example --> https://example.com/
https://omg.lol/dakota/example --> https://example.com/

https://dakota.omg.lol/example/wut --> https://dakota.omg.lol/
https://dakota.url.lol/example/wut --> https://meta.omg.lol/info/url.lol
https://omg.lol/dakota/example/wut --> https://meta.omg.lol/info/url.lol

**Comment by newbold** [comment]
I see what happened — should have it fixed up soon! Thanks for letting me know about this.

**Comment by newbold** [comment]
OK, I've got _most_ of this resolved... the only one that still doesn't work (and I'm actually not sure if it ever worked, heh) is the first one — `https://dakota.omg.lol/example/wut` still redirects back to your profile page. That's going to take some work to untangle but I can at least confirm that the `url.lol` version works as it did previously! I'll update this once the other issue has been fixed as well.

**Comment by dcchambers** [comment]
As always a super speedy fix! thanks!

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://github.com/neatnik/omg.lol/issues/160

**Comment by newbold** [comment]
Finally got the rest of this working, more or less! http://dakota.omg.lol/example/wut
