### ISSUE TITLE
Update Letterboxd icon

### ISSUE THREAD

**Issue by jmjordan** [neatnik/omg.lol#165]
Can you change the Letterbox.com icon to the three dots version instead of the L version as it is more recognizable?

https://letterboxd.com/about/brand/

<img width="699" alt="Screen Shot 2021-11-20 at 3 11 06 PM" src="https://user-images.githubusercontent.com/210460/142743466-931a6b4b-1fb0-4331-855f-44ff81871b00.png">

https://a.ltrbxd.com/logos/letterboxd-decal-dots-pos-mono-500px.png

**Comment by newbold** [comment]
Heck yes I can! Will knock it out after dinner. Thanks for letting me know about that.

**Comment by newbold** [comment]
OK, this is all set now! Thanks again.

**Comment by jmjordan** [comment]
Awesome work! Thanks!
