### ISSUE TITLE
Commenting out profile items doesn't function as expected

### ISSUE THREAD

**Issue by chxseh** [neatnik/omg.lol#167]
Basically as the title says. If I comment out a profile item by wrapping it in `<!-- itemHere -->` it *does* hide the link, but the font awesome icon is still present, causing this fun mess.  
![img](https://i.chse.dev/fcJGvq)

**Comment by newbold** [comment]
Ugh, that's not cool. I can fix it soon though! Will update when done.

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605846533313

**Comment by newbold** [comment]
This has been resolved.
