### ISSUE TITLE
Add postype.com to logo types

### ISSUE THREAD

**Issue by revi** [neatnik/omg.lol#172]
https://www.postype.com - More of deviantart but has local payment system baked in… 

All I could find was a webp logo in [Google Play](https://play.google.com/store/apps/details?id=com.postype.play), or the png one in [their team blog (Korean)](https://team.postype.com/post/6927368) ([png, rehosted on discord due to access controls](https://cdn.discordapp.com/attachments/649515595087478788/913012267602309140/c6fee495783cf622e1393d9a35807d9f.png)).

**Comment by newbold** [comment]
All set!
