### ISSUE TITLE
couple of issues with the sunkissed theme selection

### ISSUE THREAD

**Issue by lakerjv** [neatnik/omg.lol#178]
1: @Catnatsuki's name is misspelled
2: their credit link goes to the wrong person :P (their twitter is https://twitter.com/catnatsuki_)

![image](https://user-images.githubusercontent.com/63261955/144670204-a07ff084-e9db-460b-9993-bc73c1c4e1ce.png)

**Comment by newbold** [comment]
Thank you so much for catching that and pointing it out. I’ve made all of the corrections!
