### ISSUE TITLE
Add support for all Font Awesome website icons in profile

### ISSUE THREAD

**Issue by theKAKAN** [neatnik/omg.lol#18]
There, I said it. Best of luck! :smile:

**Comment by newbold** [comment]
Experimenting with something on this. On my own profile I have a profile item that looks like this:

`/fa-magic-wand-sparkles/Working on [OMG.LOL](https://omg.lol)`

If a profile item begins with a string encased in forward slashes (and if that string begins with `fa-`) then that icon will be used. Only works with `fa-solid` icons, which are what's in Font Awesome's free icon set. It's a start!

**Comment by theKAKAN** [comment]
This breaks the headers, for now...
![image](https://user-images.githubusercontent.com/22027824/126937173-68e6803d-e969-4f7c-b186-d2632e0fcf84.png)

Also, for the future, can you let us decide where, in our text, to add the free-icons ?

**Comment by newbold** [comment]
I'll follow up with you on Discord on this!
