### ISSUE TITLE
ham radio callsign icon?

### ISSUE THREAD

**Issue by lakerjv** [neatnik/omg.lol#181]
it could work like callsign://[Example] shows /fa-broadcast-tower/?

yes this is very niche but im planning on getting certified next year so it would be wonderful if i could show my callsign in a cool way :)

**Comment by newbold** [comment]
Sorry for the wait! This is now finished. Note that in the upcoming new version of the profile manager, instead of `callsign://K2AMH ` you’ll be able to do `K2AMH {callsign}` or `K2AMH {ham}`. Coming soon!

**Comment by lakerjv** [comment]
cool thanks!! :)
