### ISSUE TITLE
Add support for more fediverse servers

### ISSUE THREAD

**Issue by GilOliveira** [neatnik/omg.lol#189]
It would be cool for the profile to support other [fediverse](https://fediverse.party/) servers like [Pixelfed](https://pixelfed.org/) and [Pleroma](https://pleroma.social/).

The profile URL scheme is the same for both of these services works the exact same way as [Mastodon](https://joinmastodon.org/), i.e. `https://instance.example/@username/`.

Similarly, the user could add them to their profile using:
```
pixelfed://@username@instance.example
pleroma://@username@instance.example
```

Thanks! 😀

**Comment by newbold** [comment]
This is great! I’ve put the current site into something of a code freeze while I’m working on the new version (which should be ready soon), but I’m going to bake more direct support for fediverse stuff into the new version. I'm adding the icon to the new icon font too!

<img width="190" alt="Screen Shot 2022-01-02 at 12 25 20 PM" src="https://user-images.githubusercontent.com/986721/147883996-a2cd9a90-4fc1-488c-b4f6-f67ee72f5d9f.png">

I’ll update this issue once everything is up and running. Stay tuned!

**Comment by GilOliveira** [comment]
@newbold Seems awesome! Love the idea of having a Fediverse icon for these kinds of services!

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605118563509
