### ISSUE TITLE
Neocities

### ISSUE THREAD

**Issue by walkxcode** [neatnik/omg.lol#191]
Would love to see a neocities icon, link to SVG file here: https://upload.wikimedia.org/wikipedia/commons/1/1c/Neocities_Logo.svg

**Comment by newbold** [comment]
That icon is kind of tough! For Font Awesome compatibility, omg.lol uses one-color, single-path icons. That one has a lot of different color elements going on and I'm not sure if I can wrangle it into a clean mono version but I'll see what I can do!

**Comment by walkxcode** [comment]
Alright

**Comment by Vukkyy** [comment]
(if not, a font awesome cat icon for `neocities.org` could work)

**Comment by newbold** [comment]
I've assigned the Neocities domain the Font Awesome cat icon in the upcoming omg.lol release, which should be in production soon!
