### ISSUE TITLE
Discord username in profile returns error

### ISSUE THREAD

**Issue by anthonycastaneda** [neatnik/omg.lol#201]
I added my Discord username in the `discord://anthony.castaneda#0666` format and the correct icon is added to my profile but the username is clickable and the link goes to `https://anthony.castaneda/#0666` which returns an error.

**Comment by newbold** [comment]
Hey Anthony! Thanks for letting me know about this. You found an interesting bug that lies at the intersection of Discord usernames with dots in them and my "make something that could be a link into something clickable" code. I've fixed it just now and you should be seeding the desired behavior now.

I'm also in the middle of a major rewrite, and the new version of the profile editor should make all of this much more sane. Stay tuned for more on that!

Sorry for the trouble here, and thanks again for reporting the issue.
