### ISSUE TITLE
Icon request: mediawiki, wikimedia

### ISSUE THREAD

**Issue by revi** [neatnik/omg.lol#208]
- [MediaWiki](https://commons.wikimedia.org/wiki/File:MediaWiki-2020-logo.svg)
- [Wikimedia Community logo](https://commons.wikimedia.org/wiki/File:Wikimedia_Community_Logo.svg)

**Comment by revi** [comment]
(For the record: I chose Wikimedia Community Logo instead of ["Wikimedia" logo](https://commons.wikimedia.org/wiki/File:Wikimedia-logo_black.svg) because [community logo has no :tm: stuff](https://meta.wikimedia.org/wiki/Wikimedia_Community_Logo#Proposal_and_withdrawal_of_trademark_protection).)

**Comment by newbold** [comment]
Hey @revi, I’ve moved this over to the brand-new, not-even-yet-announced omg.lol Feedback Forum! You can track its status here: https://feedback.omg.lol/16604906021084

**Comment by newbold** [comment]
These have been added to the custom icon font. They’ll be live in a few days when we switch over to the new version of the service!

Added in e9ace2ced32ededa8c530618b707bd69ee889717.

**Comment by vtheskeleton** [comment]
Adam said sunday is the planned release

**Comment by lxjv** [comment]
is this what i get for not reading IRC this morning or am i just dum

**Comment by vtheskeleton** [comment]
no he said it like more than a day ago lol
