### ISSUE TITLE
Override link icons

### ISSUE THREAD

**Issue by jasonburk** [neatnik/omg.lol#212]
Add ability to override link icons with FA ids.

**Comment by lxjv** [comment]
you can already do that by using /fa-icongoeshere/! it only works with free solid icons however

**Comment by jasonburk** [comment]
> you can already do that by using /fa-icongoeshere/! it only works with free solid icons however

Thanks!

For anyone else wondering here is an example:

To add a unicorn to `https://mydomain.com` it would look like this

`/fa-unicorn/https://mydomain.com`
