### ISSUE TITLE
PayNym support

### ISSUE THREAD

**Issue by rapidlab309** [neatnik/omg.lol#214]
Add PayNym link to profile item, referring to paynym.is/+rapidlab309
PayNyms are reuseable Bitcoin payment address, safely posted without a privacy concerns.

Thanks!

**Comment by newbold** [comment]
Hey, sorry for the delay! This has been added to the update that’ll be launching around the end of the month. If you drop a PayNym URL in your profile, it’ll detect it and display a Bitcoin icon. Thanks for the suggestion!

<img width="241" alt="Screen Shot 2022-10-06 at 11 59 35 PM" src="https://user-images.githubusercontent.com/986721/194465262-f0ef7a45-1191-48aa-8e29-5e253d1f0d1e.png">

**Comment by rapidlab309** [comment]
Nice, glad to hear that!
Is there a chance it would be with PayNym logo, instead of Bitcoin? Could be found in here: 
https://github.com/sparrowwallet/sparrow/blob/master/src/main/resources/image/paynym.png
