### ISSUE TITLE
[Bug] Cannot use `wut` on a PURL with a custom domain

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#228]
If I type [https://faisal.url.lol/addressbook/wut](http://faisal.url.lol/addressbook/wut) - the preview page works as expected, but if I try using a custom domain linked to omg.lol and try it, eg: https://faisal.fm/addressbook/wut it takes me to the PURL homepage instead of the preview.

**Comment by fm** [comment]
Actually, I just realized that PURLs no longer work on a custom domain unless you mark your external domain as a PURL route.

**Comment by newbold** [comment]
All of this has been addressed as of now. Sorry for the delay! Here’s what’s up:

1. `/wut` and `/info` paths now show the correct interstitial page, and these will work on **any** PURL page, regardless of whether it’s on url.lol, your profile (fm.omg.lol/purl/wut), or a custom domain (custom.tld/purl/wut).
2. PURLs work on custom domains now, even if they’re not designated as PURL domains. For instance, [foobar.cool/purl](https://foobar.cool/purl) is a live custom domain attached to the `@foobar` address, configured to use the web/profile setting in the Switchboard, but /purl resolves to a real PURL and should take you to a Wikipedia entry on knitting.
3. For custom domains designated as PURL domains, you can now define a custom URL in the Switchboard that will be used whenever someone visits the root/base of the custom PURL domain. To activate this on an existing custom domain that's already in use with PURLs, you'll just need to toggle that setting in the Switchboard to something other than "PURLs" and back to "PURLs", and then you'll see the new field to the right where you can drop that URL in.

Let me know if you have any questions about any of this, or if you run into any issues. Thanks!
