### ISSUE TITLE
Add Apple touch buttons

### ISSUE THREAD

**Issue by lxjv** [neatnik/omg.lol#240]
### Bug Description

add touch images so bookmarks dont look like this 
![5BDE5A55-91A2-4F35-97EF-0BBD3C18C43D](https://user-images.githubusercontent.com/63261955/195827325-1a5db3d1-6eb7-44d2-80c4-3bfa8485f19a.jpeg)

### Steps to Reproduce

click add to home screen on home.omg.lol through safari

**Comment by newbold** [comment]
![7C4C7A95-27D0-4109-9EC3-78EF34AD9BC8](https://user-images.githubusercontent.com/986721/196544391-ae016693-911b-4a21-925a-9b3b8d7a04b6.jpeg)

All set!

**Comment by lxjv** [comment]
wehay!
