### ISSUE TITLE
[Bug] If user needs to authenticate before OAuth authorization query isnt preserved

### ISSUE THREAD

**Issue by vtheskeleton** [neatnik/omg.lol#251]
### Bug Description

If an user is logged out when authorizing an oauth application, query isnt kept after logging in to omg.lol.

### Steps to Reproduce

1. log out of omgalol
2. click a log in with omg.lol link somewhere, like [here](https://neatnik.net/adam/bucket/omgloloauth/)
3. You are prompted to log in, do so
4. observe the error message caused by query not being kept

**Comment by newbold** [comment]
Finally fixed this!
