### ISSUE TITLE
[Bug] PURLS page still has staging warning

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#253]
### Bug Description

<img width="1304" alt="Screen Shot 2022-10-16 at 11 30 51 AM" src="https://user-images.githubusercontent.com/3654256/196028310-4f3bc63f-80b6-4266-971b-e0b9d5493dff.png">

### Steps to Reproduce

- Go to https://home.omg.lol/address/$address/purls
- See warning

**Comment by newbold** [comment]
Fixed. Thanks!
