### ISSUE TITLE
[Bug] PURLs can be blank

### ISSUE THREAD

**Issue by identithree** [neatnik/omg.lol#267]
### Bug Description

A PURL's name can be blank, leading to it being unable to be edited/deleted.

### Steps to Reproduce

1. Create a PURL without a name
2. Observe the fact that you cannot delete/edit it.
3. Profit

**Comment by identithree** [comment]
Suggestion alongside: If the name is blank, generate 8 alphanumeric characters for the name.
Also, if possible, please delete the PURL on my account.

**Comment by newbold** [comment]
All set! Sorry for the delay on this. PURL names are now validated properly and blank records have been removed (there were, uh, a bunch).
