### ISSUE TITLE
Add option to hide profile footer

### ISSUE THREAD

**Issue by Vukkyy** [neatnik/omg.lol#272]
### Bug Description

See title, example here:
![image](https://user-images.githubusercontent.com/46850780/196051078-bbc273bd-eadc-430a-8d4e-7fa54ec71d4e.png)

### Steps to Reproduce

1. Switch to the naked theme.
2. Observe.

### Expected Behavior
Prami would be a "little" smaller, or not there at all.

**Comment by newbold** [comment]
It’s working as intended, more or less! The naked theme removes all styling/theming, leaving styling up to the individual user. What’s missing is the ability to hide the footer, which will be added soon.

**Comment by byemc** [comment]
> Naked theme shows giant Prami 
I don't see anything wrong here

**Comment by vtheskeleton** [comment]
i saw this pop up in firehose and had alot of questions at first

**Comment by Vukkyy** [comment]
If it's "working as intended", that's a little silly behavior, but not a bug then. Closing as not planned.

**Comment by newbold** [comment]
<img width="640" alt="Screenshot 2022-10-30 at 2 22 32 AM" src="https://user-images.githubusercontent.com/986721/198865556-e78bdb7e-3470-430b-b795-85ddcfa3f39e.png">

You can now hide the footer entirely, as an option, which pairs nicely with the Naked theme for true profile nudity.

**Comment by byemc** [comment]
@fm he did the thing
