### ISSUE TITLE
Hidden statuses are not actually hidden 

### ISSUE THREAD

**Issue by Vukkyy** [neatnik/omg.lol#320]
### Bug Description

If you choose to only have statuses from the past 24 hours or a month displayed, old ones are still accessible in various places.

### Steps to Reproduce

(make sure to replace "foobar" with your address in the following links)

#### Preparing
1. Go to https://home.omg.lol/address/foobar/statuslog
2. Make sure you have a status older than 24 hours (and no statuses younger than that, if reproducing the "latest status" version)
3. Set "Show on your Statuslog:" to "Statuses from the past 24 hours" if you haven't already
##### Through the embed
1. Go to https://foobar.status.lol, you should see your statuslog with no statuses
2. Observe your latest status still being visible in the meta tags
![image](https://niko.is-ne.at/5Lbm9Lr11.png)
##### Through the API
1. Go to https://api.omg.lol/address/foobar/statuses/latest
2. Observe your old status!
#### Seeing all of the statuses
1. Go to https://api.omg.lol/address/foobar/statuses
2. Observe your old statuses!

**Comment by newbold** [comment]
I should probably clarify this in the documentation somewhere, but the “Show on your Statuslog” setting is meant to indicate a _display preference_ for status.lol, and does not manage broader access to or visibility of entries outside of the defined time period. Everything in a Statuslog is public and accessible via the API. This ensures that allow other client implementations can manage different display options that may be desired in other contexts. Deleting a statuslog entry is the only way to ensure that it won’t show up in the API.

**Comment by Vukkyy** [comment]
Fair enough. I threw this in as a bug report as I remember this was suggested under the rationale of not wanting old statuses to remain, which the option doesn't really help with when old statuses are this easily accessible.

Back to manually deleting things I go...
