### ISSUE TITLE
Geocaching.com icons

### ISSUE THREAD

**Issue by ThijsNameIsTaken** [neatnik/omg.lol#33]
As the title suggests. I would send you a link to how a profile URL looks like but the website only shows me a generic /p/default.aspx link.

**Comment by newbold** [comment]
I’ve linked [fa-magnifying-glass-location](https://fontawesome.com/v6.0/icons/magnifying-glass-location) with geocaching.com for now. It's not perfect, but I think it conveys the right spirit until I can figure out the best way to extend Font Awesome.
