### ISSUE TITLE
Better markdown support

### ISSUE THREAD

**Issue by theKAKAN** [neatnik/omg.lol#35]
Adding `#` and the text makes it look like a header.  
Adding `##` should've made it smaller, but instead makes it look like normal text...

This is with a single preceding `#`:  
![image](https://user-images.githubusercontent.com/22027824/126909714-3fd022f3-f821-43b3-a807-b9dab702e986.png)

This is with `##` before the text:  
![image](https://user-images.githubusercontent.com/22027824/126909744-4658fc1a-b3fa-4021-8a0c-8f7066a41b45.png)

And here's what I expected would happen:
![image](https://user-images.githubusercontent.com/22027824/126909789-d07336dc-3bc2-4c37-83eb-70ae2d67a724.png)

**Comment by newbold** [comment]
This should be good to go now!
