### ISSUE TITLE
Move social.lol images to a CDN

### ISSUE THREAD

**Issue by lxjv** [neatnik/omg.lol#355]
no procrastinate @newbold

**Comment by newbold** [comment]
https://user-images.githubusercontent.com/986721/199399914-d65932bd-ec56-4337-b594-7054e5c8a6cd.mov

Just kicked off the sync! Looks like it may take a while, but I’ll let it do its thing.

**Comment by lxjv** [comment]
"social.lol media has been moved to a CDN" - adam on irc 2022
