### ISSUE TITLE
[Icon] Ecosia Tree Store and Search Engine

### ISSUE THREAD

**Issue by Mar0xy** [neatnik/omg.lol#357]
### What service is this for?

The Ecosia Tree Store(Ecosia is a German based Search Engine which plants a tree with each search with all the certificates and etc) lets you spend money to plant trees for specific causes you can select on https://plant.ecosia.org/collections/trees

### What are their domain names?

plant.ecosia.org
ecosia.org (search engine could be included)

### Do you have a link to a SVG of their logo?

https://cdn-static.ecosia.org/static/icons/safari-pinned-tab.svg

**Comment by newbold** [comment]
Nice one, thanks! This is live now: https://omg.cache.lol/profiles/icons/omg.lol-icons.html
