### ISSUE TITLE
Make a list of canonical service domains

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#359]

**Comment by lxjv** [comment]
omg.lol
home.omg.lol
social.lol
status.lol
status.omg.lol
url.lol

**Comment by Vukkyy** [comment]
paste.lol

**Comment by Mar0xy** [comment]
profile.omg.lol

**Comment by lxjv** [comment]
thnak you everyone

**Comment by newbold** [comment]
Published at https://home.omg.lol/info/service-domains. Thanks!
