### ISSUE TITLE
Icon even custom text

### ISSUE THREAD

**Issue by theKAKAN** [neatnik/omg.lol#36]
As of now, we only get the FA icon if we directly put the profile link in the text area( _be it Github, Twitter or any of the supported sites_ ), yet if we put them alongside custom markdown, they're rendered like normal links. That doesn't look as nice :stuck_out_tongue:

**Comment by newbold** [comment]
I thought I had this working — can you share an example of where this is happening? If you do something like `[This is where I put all of my code](https://github.com/username)` it should be displaying the GitHub icon, I think.

**Comment by theKAKAN** [comment]
Okay, it didn't work on my profile yesterday, but now it does. Yay!  
But there's still one issue, I think?  
If you put a link in this format: `[Text](link)` it still doesn't show the link icon for unsupported sites. Example:
![image](https://user-images.githubusercontent.com/22027824/126936860-2a2de3fa-e87a-4439-86c2-630abb41675b.png)

**Comment by theKAKAN** [comment]
Okay, wait, now the icons are gone again( _it worked 12h ago!!_ ):
![image](https://user-images.githubusercontent.com/22027824/126998846-06fee61a-7808-4618-a512-e445ddd0fd94.png)
And this is how they look in my profile settings:
![image](https://user-images.githubusercontent.com/22027824/126999010-7e1cdccb-2a9a-4aec-aec7-b2d7ebb04cd1.png)

**Comment by theKAKAN** [comment]
Yay! :D
