### ISSUE TITLE
[Bug] Fix issue with Keybase proofs

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#365]
Reported on IRC:

`When I try to do a proof with keybase (both the mobile and Mac desktop app), I end up on a page that says "This is the future home of an [omg.lol](http://omg.lol/) member!" Just looking at the params in the URL, it looks "normal" meaning the remote_username param is my keybase username, and the username param is my [omg.lol](http://omg.lol/) username. I've revoked and tried again a few times. Each time I get that page, and when I look in the keybase app/page it tells me [omg.lol](http://omg.lol/) is unreachable and shows the proof in an incomplete state.`

**Comment by Vukkyy** [comment]
> I end up on a page that says "This is the future home of an [omg.lol](http://omg.lol/) member!

This is because the URL starts with https://omg.lol/meta.

**Comment by newbold** [comment]
This has been resolved.

**Comment by williamrowell** [comment]
I'm still seeing this, as of last night and this morning.

**Comment by williamrowell** [comment]
I never get to that point.  Note that the existing proof is broken, so I chose to overwrite.

```bash
❯ keybase prove omg.lol billy
You already have a proof for billy@omg.lol; overwrite? [y/N] y
Please click on the following link to post to omg.lol:

https://omg.lol/meta/keybase/new-profile-proof?remote_username=williamrowell&username=billy&token=<token>&kb_ua=mac:6.0.1

Checking will continue while you go authorize the proof on omg.lol. To cancel hit C-c.
```

At this point, I wanted to make sure that there wasn't an issue with an extension, so instead of clicking the link, I copied and pasted into a Chrome Incognito window.  I was asked to log into omg.lol.  I did, and entered my 2FA.  Then I got a blank window with this url: `https://home.omg.lol/keybase`.

**Comment by newbold** [comment]
OK, that’s helpful. Just added some (hopefully helpful) debugging stuff to the Keybase proof handler; can you give this another shot and let me know if you get any new output? Hopefully this time you’ll get _something_ besides a blank screen.

**Comment by williamrowell** [comment]
Happy to try help.  Tried again with the same procedure.

This time the browser displayed: `Missing required parameter: username`

**Comment by newbold** [comment]
OK, bumping up debug efforts once more. This time, can you copy and paste the URL that Keybase provides (the one that starts with omg.lol/meta), but before visiting, can you add `&debug` to the end?

This will invoke a debug mode which should provide output like this:

<img width="431" alt="Screenshot 2022-11-18 at 11 15 05 PM" src="https://user-images.githubusercontent.com/986721/202833664-b508cb5f-ea73-4632-9b6a-a58b20a1dc6e.png">

Hoping we get something more interesting/useful there! If you can let me know what you see (feel free to remove anything sensitive) I'd appreciate it.

**Comment by williamrowell** [comment]
I tried this again in Chrome Incognito, and got the same result as above.

I tried again, but this time in Safari (where I was already logged into omg.lol), and the proof went through. I'm sorry, I'm really not sure what was different.
