### ISSUE TITLE
DNS hostname not fetched correctly when editing

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#386]
### Bug Description

When editing a DNS record, the system expects a FQDN in the hostname; however only the subdomain gets fetched into the field, and the user has to manually edit the name to add the `omg.lol` domain part

![8932D2BE-6636-4FBF-9615-A37143BB1B67](https://user-images.githubusercontent.com/3654256/202875988-facf7b16-c5fc-4acc-93b5-df2eeaa0fbdb.png)

### Steps to Reproduce

- Edit an existing record
- Save without modifying the hostname
- System will throw an error that it expects an FQDN

**Comment by newbold** [comment]
Thanks! This has been fixed. 😄
