### ISSUE TITLE
Waze Map Editor profile item

### ISSUE THREAD

**Issue by musa11971** [neatnik/omg.lol#39]
It would be awesome if Waze Map Editor profile links could render nicely in OMG.LOL. A Waze Map editor is a volunteer who edits the map and handles map problems for the popular navigation app Waze.  

Currently the profile item is shown as follows:
<img width="393" alt="Screenshot 2021-07-25 at 23 56 02" src="https://user-images.githubusercontent.com/21341801/126914667-ff4b25c6-9ae8-4af6-8462-2185d5c1903c.png">

Wouldn't this:

![xx](https://user-images.githubusercontent.com/21341801/126914740-dd728a81-6e12-4841-8124-a08b4a061974.png)

look much nicer 🙂 

I understand if this won't get added for being so specific. Might not even get used by anyone besides myself, but I figured I'd just request and see if there is a possibility to get this added.

**Comment by newbold** [comment]
You got it my dude. Refresh your profile!
