### ISSUE TITLE
[Bug] Hostnames in DNS editor post provider migration

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#396]
### Bug Description

Follow up to #386 

After the migration, it seems that entering your omg.lol subdomain duplicates it _(see top record)_

Also, editing an existing record, appends the domain to the name field, which is no longer needed and creates a malformed record.

<img width="1243" alt="Screenshot 2022-11-26 at 11 01 23 AM" src="https://user-images.githubusercontent.com/3654256/204083796-3c3bd221-5769-42da-aeab-c8b6707d9404.png">

 Instead, we should only return the subdomain host (or @, if on the apex).

<img width="1256" alt="Screenshot 2022-11-26 at 11 24 41 AM" src="https://user-images.githubusercontent.com/3654256/204084039-6704961d-f117-41a8-99eb-b6156eff9f47.png">
<img width="1244" alt="Screenshot 2022-11-26 at 11 24 16 AM" src="https://user-images.githubusercontent.com/3654256/204084041-23830464-9ca9-4805-ac78-13906d17b729.png">

Lastly,

In the SRV, we should drop the first zero from the placeholder test, as that is the priority being handled by the next field, and drop the user's domain from the name as per above.

<img width="1263" alt="Screenshot 2022-11-26 at 11 27 23 AM" src="https://user-images.githubusercontent.com/3654256/204084127-8c79500d-0f12-402e-a1f7-d4d6fcb495c3.png">

and replace `text` with an `@` to make it more clear?

<img width="1256" alt="Screenshot 2022-11-26 at 11 27 28 AM" src="https://user-images.githubusercontent.com/3654256/204084158-7702dfe5-afc3-4028-a5f6-56616837eda2.png">

**Comment by newbold** [comment]
All fixed! Thanks for your keen eye and for taking the time to report everything. 👍
