### ISSUE TITLE
[Bug] "Snip" renders incorrectly for PGP keys with special characters in comments.

### ISSUE THREAD

**Issue by williamrowell** [neatnik/omg.lol#400]
### Bug Description

On the account->keys page, the `snip` renders incorrectly for my pgp key.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/627365/204122341-5405f917-4359-4ac9-b626-f3f3d67cf60e.png">

I imagine this is due to the email address comments (e.g., `Comment: First Last <account@domain.com>`) embedded in the PGP public key block.

### Steps to Reproduce

Upload a PGP Public Key with embedded email addresses.  For example, you can find one linked from my webpage for account `billy`.  Not linking the key to avoid adding all of my email addresses to the index on GitHub.

**Comment by newbold** [comment]
That was exactly the problem — thanks for noticing and letting me know about it! All fixed now. 👍
