### ISSUE TITLE
[Icon] Cohost

### ISSUE THREAD

**Issue by nuztalgia** [neatnik/omg.lol#403]
### What service is this for?

Cohost. Here's a description from their home page:

> cohost is a new social media platform built from the ground up by a small team of developers and designers who like sharing things on the internet.

Example page: https://cohost.org/nuz

### What are their domain names?

https://cohost.org/

### Do you have a link to a SVG of their logo?

- [Cohost Logo](https://www.svgviewer.dev/s/5ZFHyz8g) (Found by inspecting source, hence the janky link.)
- [Original Eggbug](https://cohost.org/static/f0c56e99113f1a0731b4.svg) (The universally loved [site mascot](https://cohost.org/eggbug).)
- [Monochrome Eggbug](https://staging.cohostcdn.org/attachment/24480043-8897-42fe-8f5e-314fc600b42d/eggbugsmol.svg) (Created by [@valpackett](https://cohost.org/valpackett/post/142420-i-monochromed-the-ve) specifically for small icons. My personal favorite!)

**Comment by newbold** [comment]
Icon added! Should be applied to any cohost.org link from this point forward (if you already have one on your profile, just republish your profile to see it). Thanks!

**Comment by nuztalgia** [comment]
It works beautifully, thank you so much! 😄
