### ISSUE TITLE
[Bug] Ellipsis (…) not stripped from weblog post slug creation if in Title: front matter

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#408]
### Bug Description

While some punctuation clearly is properly stripped from the Title: value when generating the post slug, the ellipsis (…) isn't, and is included in the slug.

**Comment by newbold** [comment]
This has been fixed in tonight’s update. There are still a few other slug generation bugs, so I’m keeping this open for now, but just wanted to let you know that the issue you raised has been addressed.
