### ISSUE TITLE
Add XMPP to the scheme/profile icon list

### ISSUE THREAD

**Issue by theKAKAN** [neatnik/omg.lol#41]
It's not there in Font Awesome, I think?  
Maybe add it from somewhere else if the license allows for it :P

**Comment by newbold** [comment]
Any suggestions for a good alternate icon from the existing collection? Would [fa-message-lines](https://fontawesome.com/v6.0/icons/message-lines?s=solid) make sense?

**Comment by theKAKAN** [comment]
@newbold thats more of a general solution... I was wondering if you could add a custom icon instead :P ?

**Comment by newbold** [comment]
Finally got custom icon support in place! The XMPP icon will now be shown when the `xmpp://` scheme is used.

**Comment by theKAKAN** [comment]
I love it! Thanks! :D
