### ISSUE TITLE
[Bug] Info link at the top of the Keys page points to the info link for Proofs

### ISSUE THREAD

**Issue by ThaMunsta** [neatnik/omg.lol#414]
### Bug Description

Title says it all but the info link on `https://home.omg.lol/address/[ADDRESS]/keys` points to `https://home.omg.lol/info/proofs` rather than `https://home.omg.lol/info/keys`

### Steps to Reproduce

1. log in
2. navigate to Dashboard
3. choose any address you own
4. navigate to Keys
5. click info link in the top right of the screen

**Comment by newbold** [comment]
Thanks so much for letting me know about this! Just fixed it. Really appreciate it!
