### ISSUE TITLE
[Bug] colon character breaks Title configuration parameter

### ISSUE THREAD

**Issue by tijs** [neatnik/omg.lol#418]
### Bug Description

When you add a title that contains a colon the characters after the colon will be dropped from the slug, e.g. this configuration:

```
---
Title: He-Man: Masters of the Universe
Date: 2021-04-03 13:58
---
```

Will end up with a slug `/he-man` instead of the full title.

### Steps to Reproduce

1. create a new post
2. copy paste the configuration example
3. check the blog post url that was created

**Comment by newbold** [comment]
Heh, I had this comment in my code:

`// todo: support colons in post metadata values`

Turns out it wasn’t too hard to fix that, so it’s now fixed! (Skeletor would be most displeased.) If you republish that page you should be good to go now. 👍

**Comment by tijs** [comment]
You have the most impressive turnaround in the business! ;)
