### ISSUE TITLE
[Bug] Weblogs: allow for unparsed strings in the post path format

### ISSUE THREAD

**Issue by GilOliveira** [neatnik/omg.lol#422]
### Bug Description

I wanted to make the default post path as `/article/`, the issue is, that gets parsed as a date-time string so the final URL ends up something like `/amWed,%2007%20Dec%202022%2008:56:00%20+000031562022-12-07T08:56:00+00:00Wednesday+00:00/`.

Could there be a way to escape the string? Something like `/"article"/`?

Loving the pre-pre-alpha 🌈

### Steps to Reproduce

Add `Post path format: /article/` to the configuration file.

**Comment by GilOliveira** [comment]
Closing as it does appear to be fixed now

**Comment by GilOliveira** [comment]
Reopening as it does seem to be broken again :sweat_smile:

**Comment by newbold** [comment]
I believe this is good to go now. 👍 (And has been for some time, but I forgot to close it, sorry.)
