### ISSUE TITLE
[Bug] setting up a www subdomain for a custom domain

### ISSUE THREAD

**Issue by tijs** [neatnik/omg.lol#431]
### Bug Description

I've followed the setup guide for custom domains setting up simply an A record for my tijs.org custom domain. While this works I seem unable to setup a www.tijs.org subdomain. I've tried both with a separate CNAME record for www and without (since the guide seems to advise to only use either an A record or a CNAME). Do I misunderstand the possibility of setting up custom sub domains exists, or am I simply missing some config?

### Steps to Reproduce

1. setup a custom domain name by pointing the root domain to the given ip address using an A record
2. setup a CNAME record for the www subdomain for the same domain, or not
3. the naked domain works, the common www subdomain is not also pointed to the omg.lol website

**Comment by tijs** [comment]
I have also tried setting up the www cname on the omg.lol DNS settings by the way. That seemed like a non-obvious but perhaps valid workaround, that too does not seem to work though..

**Comment by fm** [comment]
Did you add `www.` as an external domain route first? Since it's technically a subdomain, the system may be expecting it separately, so when it doesn't know which profile to route it, it sends it to the homepage.

**Comment by tijs** [comment]
I have now added it again as a en external subdomain using a CNAME entry in the omg.lol DNS but that too does not seem to work.

**Comment by fm** [comment]
Just to double check, you added `www.` as an external domain like this?

<img width="967" alt="Screenshot 2022-12-18 at 12 23 31 PM" src="https://user-images.githubusercontent.com/3654256/208295644-6dcc1783-60a4-4ed4-a2fd-8ec5b650038f.png">

**Comment by tijs** [comment]
OMG I forgot to do that. Ok that makes complete sense now. For some reason I assumed some sort of auto resolving magic but of course I just needed to set up both the root and subdomain and my registrar and at omg.lol. Thanks that did the trick!
