### ISSUE TITLE
[Bug] ORCID on profiles

### ISSUE THREAD

**Issue by GilOliveira** [neatnik/omg.lol#433]
### Bug Description

I've listed this as a bug and not a icon request because it seems like this is already partially implemented.

[ORCID](https://info.orcid.org/what-is-orcid/) is the provider of a persistent digital identifier for researchers, it's the *de facto* standard way to unambiguously identify an author of a scientific publication.

Each person is assigned an ORCID iD, which follows a [predictable structure](https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier) in the format `0000-0000-0000-000X` (last character is a check-digit in the 0-X range). ORCID profiles also follow a predictable pattern: `orcid.org/0000-0000-0000-000X`.

What I believe should be the correct behaviour is something like this:
<img width="258" alt="ORCID icon followed by ORCID iD" src="https://user-images.githubusercontent.com/1360438/208399489-2c14f9bf-6479-4b11-8d46-c8320c803bd4.png">

However the current implementation is kind of inconsistent, just putting the URL displays the ORCID iD correctly but displays the default link icon, and adding the `{orcid}` Font Awesome slug displays the correct logo but the full URL.

### Steps to Reproduce

1. Do science-y things
2. Plop in your ORCID profile URL in your profile and get this:
<img width="260" alt="ORCID iD with default link logo" src="https://user-images.githubusercontent.com/1360438/208400433-a6ebfdba-7bc4-4fff-b6e5-2fb6f638e02a.png">
3. Add `{orcid}` to the entry and get this:
<img width="394" alt="ORCID logo with full ORCID profile URL" src="https://user-images.githubusercontent.com/1360438/208400736-8a57f0af-61f8-4939-988c-d3d6374f639b.png">

**Comment by newbold** [comment]
OK, this is all set now. I’ve associated the ORCID icon with the orcid.org domain, and now you’ll get the expected results — just drop your orcid.org URL in a profile item and it’ll render nicely without the need to tag in the `{orcid}` icon (the icon will appear automatically). Thanks for pointing this out!
