### ISSUE TITLE
[Bug] weblog.lol: Multiple advanced variables on one line only render one

### ISSUE THREAD

**Issue by m4xic** [neatnik/omg.lol#434]
### Bug Description

The example blog post uses an advanced variable called `spanmod`. It is defined as below:

```
Spanmod: <span class="$class">$content</span>
```

---

Using the following code in the post body...

```
{spanmod:class=1&content=1} {spanmod:class=2&content=2} {spanmod:class=3&content=3}
```

...produces the output below:

```html
<span class="1">1} {spanmod:class</span>
```

when I would expect it to output...

```html
<span class="1">1</span> <span class="2">2</span> <span class="3">3</span>
```

### Steps to Reproduce

Example blog post: https://maxic.weblog.lol/2022/12/webloglol-bug-report

Raw blog post content: https://maxic.paste.lol/weblog.lol-bug-report.md/raw

**Comment by newbold** [comment]
This has been resolved. Sorry for the trouble! Turns out it was due to a missing `?` in the regex. _Regex, amirite?_

**Comment by m4xic** [comment]
> *Regex, amirite?*

something something hard problems in computer science :)

---

Thank you for such a quick reply! It looks like it renders properly now, but only the first advanced variable of a given type given on a line will be rendered each time (e.g. in the example, it should output `1 2 3` but in [this post, for example](https://maxic.weblog.lol/2022/12/webloglol-bug-report) it outputs `1 1 1`).

Sorry to be a pain, I imagine this is a super tricky bit of functionality to add but just wanted to flag so you're aware!

**Comment by newbold** [comment]
Ah, sorry — found and fixed! It was due to a sloppy string replacement process that I got away with only because I hadn’t attempted to do more than one replacement of the same variable on a page. Should be good now, but I won’t tempt fate by closing this like I did I last time. Let me know how it looks on your end!

**Comment by m4xic** [comment]
Thank you! That issue seems to be fixed! 🎉 

Slightly different one - an advanced variable that had previously been working no longer replaces some of the `$`parameters when including it. I can create a new issue if you'd prefer.

---

My configuration contains...

```
Footnote: <label for="fn-$fnid">$emoji</label><input type="checkbox" id="fn-$fnid"><small class="$theme">$content</small>
```

...which I've included in the [blog post from before](https://maxic.weblog.lol/2022/12/webloglol-bug-report) as...

```
{footnote:fnid=1&theme=danger&emoji=x&content=content1}
{footnote:fnid=2&theme=danger&emoji=x&content=content2} 
{footnote:fnid=3&theme=danger&emoji=x&content=content3} 
```

...which renders as...

```html
<label for="fn-$fnid">$emoji</label><input type="checkbox" id="fn-$fnid"><small class="$theme">content1</small>
<label for="fn-$fnid">$emoji</label><input type="checkbox" id="fn-$fnid"><small class="$theme">content2</small>
<label for="fn-$fnid">$emoji</label><input type="checkbox" id="fn-$fnid"><small class="$theme">content3</small>
```

Weird that `$content` seems to work properly, but none of the other variables do?

---

Sorry to keep adding to this 😭 none of the fixes are urgent if that helps!

**Comment by newbold** [comment]
As someone who simply crushed the whack-a-mole game at Chuck-E-Cheese in the 80s, I’m ready to keep at this until everything works flawlessly. Pretty sure I’ve got this where it needs to be now, but let me know if you encounter any other glitches.
