### ISSUE TITLE
[Bug] Cannot create new record after adding one

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#435]
### Bug Description

When I add a new DNS record, I can't create a new one until I click on the `DNS` heading to refresh the page. 

<img width="1098" alt="Screenshot 2022-12-19 at 6 31 53 PM" src="https://user-images.githubusercontent.com/3654256/208485373-af4b1e4b-086b-42d6-a070-345cfdaeb38f.png">

### Steps to Reproduce

1. Add new record and save it
2. You can't create another record until you click the `DNS` tab to refresh the page

**Comment by newbold** [comment]
This should be working more nicely now. Sorry for the trouble!
