### ISSUE TITLE
[Bug] weblog.lol search not returning all matches

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#444]
### Bug Description

Search doesn’t seem to return all matches for search terms.

### Steps to Reproduce

On my blog, for example, a search for “burnout” does return plenty of posts, but oddly not, for example, one titled “Today I Learned About Autistic Burnout” where the term occurs several times.

**Comment by newbold** [comment]
Should be fixed now — thanks for letting me know about that. Found a weird conditional that was omitting certain things based on length that never should have been there. Sorry!
