### ISSUE TITLE
[Icon] 

### ISSUE THREAD

**Issue by calebhearth** [neatnik/omg.lol#450]
### What service is this for?

Mastodon

### What are their domain names?

Ruby.social, dice.camp

**Comment by newbold** [comment]
Awesome, thanks — they’re in there now!

**Comment by calebhearth** [comment]
Thanks!On Dec 31, 2022, at 8:25 PM, Adam Newbold ***@***.***> wrote:﻿
Awesome, thanks — they’re in there now!
