### ISSUE TITLE
Icon request: Tor

### ISSUE THREAD

**Issue by 0xdade** [neatnik/omg.lol#493]
I'd love to link my hidden service version of my website on my omg.lol page, but attempting to use font-awesome onion (`{onion}`) just results in showing the default font awesome flag, and `{tor}` doesn't work either.

Given the unique structure of onion addresses, automatically picking the correct icon when the domain part of a url ends in `.onion` seems like it would be pretty doable. Time permitting, I might try to fulfill this issue myself -- but opening in case anyone else can quickly get to it before me :)

Until then, I'll just use {user} for my regular website and {user-secret} for my hidden service version of my website :)

**Comment by newbold** [comment]
Should be good to go now! URLs ending in .onion will get the icon automatically, and the `{tor}` tag will also apply it.

<img width="1285" alt="Screenshot 2023-01-09 at 5 09 06 PM" src="https://user-images.githubusercontent.com/986721/211418357-58d3b904-0ec5-4a07-a96f-73257ebd2800.png">

You may need to refresh a couple of times for the custom icon font to reload. Let me know if you run into any issues!

**Comment by 0xdade** [comment]
Awesome, thanks for such a quick turnaround time!
