### ISSUE TITLE
Profile Icon: Nicovideo

### ISSUE THREAD

**Issue by ameyoyo** [neatnik/omg.lol#496]
Hello, may I request a profile icon for a site called [nicovideo](https://www.nicovideo.jp/)?
The icon would hopefully be something along the lines like this: 
![image](https://user-images.githubusercontent.com/47435073/211443722-b33953df-6114-4dd3-b953-aa2a0bb54c68.png)

thank you! i don't think i seen too many github issues for icon requests so hopefully i'm still in the right place

~ omg.lol/ame

**Comment by newbold** [comment]
OK, that’s in there now! The icon is called `{niconico}` and any profile item with a nicovideo.jp URL will use it automatically. Might take a couple of browser refreshes to see it (thanks, caching) but it’s live!
