### ISSUE TITLE
[Bug] Directory API behavior is inconsistent with doc 

### ISSUE THREAD

**Issue by wayneyaoo** [neatnik/omg.lol#499]
### Bug Description

The "List Address Directory" API [per doc here](https://api.omg.lol/#token-get-directory-retreive-the-address-directory) requires authentication with token, but it's actually public accessible. Not sure if this is intended or the doc needs updating.

### Steps to Reproduce

Go here: https://api.omg.lol/directory in private browsing

- Expected behavior: 401 without authentication.

- Actual behavior: address directory is returned.
  ![image](https://user-images.githubusercontent.com/20643897/211584944-cd0bf9ee-cb83-4885-ba8d-f64dc25331a8.png)

**Comment by newbold** [comment]
Thanks — this is resolved! (It is intended to be an open endpoint, so I’ve corrected the documentation.)
