### ISSUE TITLE
[Bug] Address expiration endpoint does not return 404 on non-exist account

### ISSUE THREAD

**Issue by wayneyaoo** [neatnik/omg.lol#500]
### Bug Description

I'm not sure if this is a bug but seems like one to me... Reporting this anyways.

Per the [public "Retrieve Address Expiration" API here](https://api.omg.lol/address/dhasdkalsdas/expiration), when I request to get the expiration info of an non-exist account, logically it should return 404, both in http status code and inside the "status code" of the content (as I see this behavior on other APIs, e.g., 401 is set in both places). But actually it returns 200 on both places. 

### Steps to Reproduce

Go here: https://api.omg.lol/address/dhasdkalsdasdhjskada/expiration in private browsing. It should return 404 but actually 200.

![image](https://user-images.githubusercontent.com/20643897/211588110-edb1e5c5-6394-49aa-830e-f9288af54dfa.png)

If this is intended behavior, I'd suggest to consider a redesign of this endpoint, as API consumer code cannot (easily) differentiate which model to deserialize to if the response code is always the same regardless of the message being different. Also it's inconsistent to other API behavior.

**Comment by newbold** [comment]
This now returns a `404`. Thanks for reporting the problem!
