### ISSUE TITLE
[Doc] inconsistent doc model and actual response model 

### ISSUE THREAD

**Issue by wayneyaoo** [neatnik/omg.lol#507]
### Bug Description

Regarding address expiration endpoint, e.g., https://api.omg.lol/address/wy/expiration

The response [specified in doc](https://api.omg.lol/#noauth-get-address-retrieve-address-expiration) is the following:

```json
{
    "request": {
        "status_code": 200,
        "success": true
    },
    "expiration": {
        "address": "penelope",
        "message": "This address expires in 21 years.",
        "unix_epoch_time": "2300941010",
        "iso_8601_time": "2042-11-30T06:16:50+00:00",
        "rfc_2822_time": "Sun, 30 Nov 2042 06:16:50 +0000",
        "relative_time": "21 years from now"
    }
}
```

But actual response is slightly different:

```json
{
    "request": {
        "status_code": 200,
        "success": true
    },
    "response": {
        "message": "This address expires in 11 months and 3 weeks.",
        "expired": false,
        "will_expire": true,
        "unix_epoch_time": "1704722794",
        "iso_8601_time": "2024-01-08T14:06:34+00:00",
        "rfc_2822_time": "Mon, 08 Jan 2024 14:06:34 +0000",
        "relative_time": "11 months and 3 weeks"
    }
}
```

Might need a doc update.

### Steps to Reproduce

See above.

**Comment by wayneyaoo** [comment]
Question: Is the doc considered a reliable source of getting correct response model? I mean if not then it's a trivial doc issue : ). Do we have OpenAPI or something that we can use to directly map Json to code?

**Comment by newbold** [comment]
@wayneyaoo Good question. It’s generally accurate but as you’ve found there are some times when responses are updated and I fail to update the documentation. I’m currently using Postman for testing and development, so that doesn’t generate OpenAPI output, but the raw source is available [here](https://github.com/neatnik/omg.lol/tree/main/api/docs).

I have updated the expiration endpoint documentation above to be consistent with the live output. Thanks for pointing out the issue!

**Comment by wayneyaoo** [comment]
@newbold I see. Thanks for the comment!

Interested in some conversion tech :)? 

So [Postman open technology proposed two tools](https://www.postman.com/postman/workspace/postman-open-technologies-convert-postman-collections-into-openapi/overview) for Postman collection conversion to OpenAPI Json:

- [Postman-to-openapi](https://joolfe.github.io/postman-to-openapi/)
- [Postman2OpenAPI](https://github.com/kevinswiber/postman2openapi)

Both have a CLI. And I tried the second one (happen to have `cargo` here) with the `Account` API and it _looks_ fine. The first one has more stars but I didn't try.
![image](https://user-images.githubusercontent.com/20643897/212126424-01338f91-35a1-4d95-9569-d9b81117f32c.png)

I would probably leverage this for faster development (model mapping, mainly) in the next few weeks to see how it works out. This also doesn't break your common workflow I believe. If the conversion is precise enough, adding an CI to make it should be low hanging fruit 😀.

Anyway just add some info here in case you missed it!

**Comment by wayneyaoo** [comment]
@newbold Hey Adam sorry for reusing the closed issue. Can I consider the Postman collection in the repo the source of true for model change? or is there any other more reliable way that I can "watch" for when there's change (since the API service is still in beta, I currently rely on my local tests)?

**Comment by newbold** [comment]
@wayneyaoo, yes, for the time being the Postman JSON output is the closest thing we have to a source of truth on the API. 👍
