### ISSUE TITLE
[Bug] Page redirection broken on API intro page

### ISSUE THREAD

**Issue by wayneyaoo** [neatnik/omg.lol#509]
### Bug Description

- Go here: https://api.omg.lol/
- Scroll down to the bottom
- Click the "Info & help" or "Legal"

Expect:
- The two links take me to the right pages

Actual:
- Endpoint not found lol

**Comment by wayneyaoo** [comment]
Seems so. I can't repro too and find a new "News & Updates" section. Someone should get it fixed (and add a new thing) : )

**Comment by newbold** [comment]
@wayneyaoo, @Vukkyy, apologies — I did indeed fix this late last night and completely forgot to acknowledge or close this. Sorry for the confusion!
