### ISSUE TITLE
[Bug] /now page is default fallback when page doesn't exist

### ISSUE THREAD

**Issue by Zacatero** [neatnik/omg.lol#516]
### Bug Description

If you have just a profile page, doing **address.omg.lol/page** (assuming that page isn't a PURL) will just fallback to the address.omg.lol. But once a /now page is made, THAT becomes the fallback for any unrecognized page url.

### Steps to Reproduce

1) Go to an address where /now is set up
2) Go to address.omg.lol/somethingrandom

**Comment by newbold** [comment]
This has been resolved. I’m also now sending a proper 404 response when there’s no content available at the requested URL, though until custom 404 pages are supported, I’ll continue to display the usual profile page.
