### ISSUE TITLE
Toss logo

### ISSUE THREAD

**Issue by revi** [neatnik/omg.lol#52]
Yeah, probably just me who will ever use it, in profile, but still…

toss ([Wikidata](https://www.wikidata.org/wiki/Q61090825?uselang=en)) is somewhat like… South Korean edition of Venmo in US. They have `toss.me` as user-configurable URL to transfer money.

Have SVG [here](https://static.toss.im/icons/svg/logo.svg) with the logo AND the wordmark. Shouldn't be that hard to remove the wordmark, I think.

**Comment by newbold** [comment]
It’s live now! Any profile item that includes a toss.me URL (either directly or in Markdown) should display the correct icon as of now.
