### ISSUE TITLE
Text color issue with Gilded theme on /now page

### ISSUE THREAD

**Issue by acfusco** [neatnik/omg.lol#524]
### Bug Description

Headers other than h1 show up with black text on black background in the name/bio portion on a /now page when using the Gilded theme. (Regular "now" section is fine.) I did a workaround on my page but attached is a screenshot.

![Now_Screenshot_2](https://user-images.githubusercontent.com/121382981/212936619-cafc6ef7-210f-4eaa-839b-a10f9f69ca55.jpg)

### Steps to Reproduce

Switch to Gilded theme when using default Markdown theme.

**Comment by newbold** [comment]
Sorry about that — this should be fixed now! I’ll need to go and do a proper audit of all of the member-submitted themes, as there could be some other cases like this that I’ve missed.

Thanks for letting me know about it!

**Comment by acfusco** [comment]
Hi. Adam:

Sorry, but this still shows up as black text. I was able to improve my workaround so it appears about the same as otherwise, so no rush as far as I'm concerned. 

Thanks,

Adam

**Comment by acfusco** [comment]
It works now! Many thanks. 

Adam
