### ISSUE TITLE
Fix evil Prami in YouTube profile picture

### ISSUE THREAD

**Issue by Vukkyy** [neatnik/omg.lol#526]
![Channel data](https://toilet.blob.gay/file/b2PaXA.png)
![Zoomed in, showing... something in its eyes](https://trash.vukky.net/file/xW1U1g.png)

Look at that thing. You don't want that in your house... do you?!

**Comment by newbold** [comment]
So, looking into this further, I’m actually not sure what I can do about it. Here’s the source image that I uploaded to YouTube:

![prami-avatar](https://user-images.githubusercontent.com/986721/213095911-056da741-b319-4850-8ff7-fd262b05a426.png)

As you can see, the eyes are perfectly solid. I think we’re seeing the result of some kind of weird resampling or compression setup that YouTube is using. I’m open to suggestions on what I can try!
