### ISSUE TITLE
[Bug] Dragging your profile picture onto itself breaks the dialog

### ISSUE THREAD

**Issue by Scotsguy** [neatnik/omg.lol#533]
### Bug Description

In the profile editor, dragging your profile picture from the upload dialog onto the upload dialog will make it stay in the uploading... state forever, because:
```js
Uncaught TypeError: file is undefined
    dropHandler https://home.omg.lol/address/one/web:808
    ondrop https://home.omg.lol/address/one/web:1
web:808:5
```
(Not all drag and drop events have files. For example, this one. I could imagine this would also happen when dragging an image from another website, or something.)

**Comment by newbold** [comment]
This should be corrected now, but let me know if you notice any other weirdness! And thanks for pointing out the issue.
