### ISSUE TITLE
[Bug] Profiles beginning with numbers other than 0 don't show in Address Directory

### ISSUE THREAD

**Issue by supleed2** [neatnik/omg.lol#539]
### Bug Description

At https://home.omg.lol/directory in the # section, only 3 profiles which all begin with 0 show, while the API returns quite a few more profiles beginning with numbers.

### Steps to Reproduce

See limited profiles at https://home.omg.lol/directory:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/21363892/213890033-7a2f58f5-9044-404e-997f-73085255b116.png">

More profiles when accessed via API:
```json
"directory": [
"0",
"0x7f",
"0xdade",
"2k",
"4",
"420",
"6",
"7au",
"8",
"8bit",
"a2",
```

**Comment by newbold** [comment]
Thanks, great catch. Just fixed!
