### ISSUE TITLE
[Bug] When clicking on "View live" of pastes the bottom button does not link the correct format

### ISSUE THREAD

**Issue by zerenxyz** [neatnik/omg.lol#551]
### Bug Description

When clicking on the Pastes "View Live" button below the paste area it takes you to page but with a small error: `[username]paste.lol/paste-name` instead of `[username].paste.lol/paste-name` which leads to a broken URL.

![image](https://user-images.githubusercontent.com/52886201/214557256-618d21b4-38f7-4043-9ca7-07e3c40ee835.png)

### Steps to Reproduce

1. Create a new paste, and save it
2. Go to a different page
3. Come back to the paste you just saved
4. Scroll to the bottom
5. Next to the []Listed check mark
6. Click on "View Live"
7. Takes you to broken URL format

**Comment by newbold** [comment]
This is fixed now—sorry for the trouble! And thanks for reporting. 🫡
