### ISSUE TITLE
[Bug] Changed post path format, now all posts 404

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#554]
### Bug Description

So I changed my `Post path format` in config last night, and didn’t notice until this morning that while all the links in `{post-list}` and whatnot updated, the posts themselves don’t appear at the new links. I tried triggering another rebuild by adding blank newlines to config and re-saving but no joy.

**Comment by newbold** [comment]
Everything looks OK on this end, but that makes me wonder if I’m looking at the wrong thing. Can you give me a URL to one of your posts that’s 404ing?

**Comment by newbold** [comment]
OK, sorry about that — I finally saw what was going on, and I was able to fix it. The code was assuming that all URLs would always be all lowercase, which was a pretty dumb thing to do, so I’ve just made a change that handles things in a case-insensitive manner. Should be good to go now!
