### ISSUE TITLE
[Bug] Status.lol embed shows "Respond" when no URL exists

### ISSUE THREAD

**Issue by rknightuk** [neatnik/omg.lol#561]
### Bug Description

Using the status.lol embed, the "respond" links shows even if no `external_url` exists on the status. For example:

https://robb.status.lol/63d3750b5c95f has no `external_url` but shows as such:

![2023-01-29 09 42 06](https://user-images.githubusercontent.com/948436/215318059-b87a783a-53fd-4108-be66-9c1d85171e53.png)

### Steps to Reproduce

- Add a status with no Mastodon cross-posting enabled
- Using the embed
- See the "respond" link shows

**Comment by newbold** [comment]
Sorry about that—fixed now!
