### ISSUE TITLE
[Icon] Open Source hardware

### ISSUE THREAD

**Issue by andypiper** [neatnik/omg.lol#566]
### What service is this for?

Similar to the OSI / Open Source Initiative logo (part of Font Awesome), it would be great to have an icon for Open Source Hardware...

https://www.oshwa.org/open-source-hardware-logo/

### What are their domain names?

https://www.oshwa.org/ (but this is more for generalised use to refer to hardware, rather than for a service / profile item)

### Do you have a link to a SVG of their logo?

https://www.oshwa.org/wp-content/uploads/2014/03/oshw-logo-outline.svg

**Comment by newbold** [comment]
Sorry for missing this one earlier. It’s included now!
