### ISSUE TITLE
[Bug] weblog.lol custom Search Template not being used

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#587]
### Bug Description

Per [here](https://omglol.news/2023/01/22/weblog-updates-some-template-flexibility-titleless-posts-and-improved-markdown-parsing) I made a custom Search Template (so I could have a search form appear on the search results page) and added `Search template: Search Template` in configuration, but search results don't load that template.

**Comment by newbold** [comment]
Thanks for catching that — I had set up tag page templates and search templates at the same time, and accidentally had the tag page template stuff in the code twice (one where it belonged, and another time where the search template belonged). Whoops. Fixed!
