### ISSUE TITLE
[Bug] Posts saved as drafts show up in tag lists on site

### ISSUE THREAD

**Issue by acfusco** [neatnik/omg.lol#590]
### Bug Description

Posts saved as drafts still appear in tag list pages on a weblog site. Screenshots attached. I have test posts under two different tags. 

Also, a deleted post called "The Smiths 2" has reappeared under a tag last, though it no longer shows up in my dashboard.

![Test_1](https://user-images.githubusercontent.com/121382981/216927676-18885bb5-da9f-43fa-b34c-254ff8dcc4d9.jpg)
![Test_2](https://user-images.githubusercontent.com/121382981/216927682-a8e0ddd2-aad1-4c8f-a3a7-7591baec715c.jpg)

**Comment by newbold** [comment]
Thanks for catching these. Interestingly, the deleted post wasn’t actually deleted (somehow), but in its metadata the `Type` value was blank, causing it to become hidden entirely within the UI. I’ve just fixed this bug, and you should now be able to fully delete the post. (Entries with empty `Type` values will also now be called out in the UI.)

Draft posts will also no longer appear on tag pages. Thanks again!
