### ISSUE TITLE
Handle cropping/resizing of profile pictures

### ISSUE THREAD

**Issue by newbold** [neatnik/omg.lol#6]

**Comment by k7hpn** [comment]
Possibly [imgproxy](https://github.com/imgproxy/imgproxy) could be employed to handle this.

**Comment by newbold** [comment]
I wound up taking the simplest approach here, which is allowing people to upload pics of any aspect ratio they want instead of enforcing a 1:1 aspect ratio. If someone wants a rectangular pic, that’s cool with me! If someone wants to crop their pic, there are a bunch of existing services that people can use. I just found out that [Adobe offers a super nice web-based Photoshop cropping tool](https://photoshop.adobe.com/crop) for free—doesn't even require a login.
