### ISSUE TITLE
clear references to classic editor

### ISSUE THREAD

**Issue by byemc** [neatnik/omg.lol#612]
>               > I vote for redirecting “/classic-editor” to “/editor” and renaming “/advanced-editor.md” to just “/editor.md" - @byemc 
> me too, ill send a PR in
> _Originally posted by @lxjv in https://github.com/neatnik/omg.lol/issues/611#issuecomment-1445381061_
            
Probably should track here until someone gets around to that (too busy procrastinating, sorry)

**Comment by byemc** [comment]
Maybe `/classic-editor` could show something like

```md
The classic web editor has been shut down. Please use the new [web editor](/editor) instead.
```

**Comment by newbold** [comment]
`/classic-editor` now redirects to `/editor`, so I think we're good now.

**Comment by byemc** [comment]
waiting for the omg.lol “bring back classic editor” chrome extension for some reasonSent from my iPhoneOn 26 Feb 2023, at 17:12, Adam Newbold ***@***.***> wrote:﻿
/classic-editor now redirects to /editor, so I think we're good now.
