### ISSUE TITLE
[Bug] weblog.lol Index: exclude not respected 

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#620]
### Bug Description

Search will surface matching pages even if those pages have ’Index: exclude` front matter.

**Comment by newbold** [comment]
This now works as intended — sorry for the trouble!

**Comment by newbold** [comment]
I just learned that this is only half fixed — it works on weblog.lol subdomains, but not on custom/hosted domains. Will have that sorted out shortly, but opening until then.
