### ISSUE TITLE
[Bug] /now pages don't have custom <head> or CSS

### ISSUE THREAD

**Issue by byemc** [neatnik/omg.lol#628]
### Bug Description

See title.

### Steps to Reproduce

1. Go to a profile page with custom CSS and a now page (like https://bye.omg.lol)
2. Go to its now page
3. Observe

**Comment by byemc** [comment]
Looks like it affects all now pages (sample size: 2)

**Comment by Liquidream** [comment]
Thx for formalising this, @byemc 👍

**Comment by byemc** [comment]
> Thx for formalising this, @byemc +1

heh, this might be a first. i once found a potentially serious vulnerability in profile pages and had to stop myself talking about it in IRC and email adam

**Comment by byemc** [comment]
Closing as @newbold as confirmed as fixed. 
![image](https://user-images.githubusercontent.com/77801870/223220541-91690871-2519-464f-aaf6-923aebf14841.png)
