### ISSUE TITLE
[Bug] weblog:lol Truncation appendix: doesn’t appear on tag pages

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#629]
### Bug Description

The configuration setting `Truncation appendix:` that’s part of titleless post handling appears in `{post-list}` but not in post lists on tag pages.

**Comment by newbold** [comment]
Fixed! Sorry about that.

**Comment by newbold** [comment]
Oh, hold up. I did fix it, but haven't pushed the change yet. Stand by.

**Comment by newbold** [comment]
Should be good now! Sorry for the false alarm.
