### ISSUE TITLE
rel=me support

### ISSUE THREAD

**Issue by revi** [neatnik/omg.lol#63]
[indieweb's description](https://indieweb.org/rel-me).

This is mostly used for mastodon's [verified link](https://docs.joinmastodon.org/user/profile/), which requires `rel="me"` method to authenticate ownership.

Example)
<img width="325" alt="image" src="https://user-images.githubusercontent.com/7630875/132673080-6831c6b1-929a-4e96-b156-6f0348eecd11.png">

**Comment by newbold** [comment]
Done!
