### ISSUE TITLE
[Bug] some.pics pages show jason.some.pics as the title

### ISSUE THREAD

**Issue by rknightuk** [neatnik/omg.lol#634]
### Bug Description

The title on all some pics pages are `jason.some.pics` 

https://robb.some.pics/
https://nath.some.pics/

![2023-03-09 13 35 40](https://user-images.githubusercontent.com/948436/224039089-3ac99a70-a949-4db9-a59a-223f78188a5c.png)

### Steps to Reproduce

Got to one of those URLs, check the title.

**Comment by newbold** [comment]
Jason’s temporary reign over the visual namespace has come to an end. Bug fixed! Sorry about that.
