### ISSUE TITLE
[Bug] some.pics mobile view breaks depending on Exif content

### ISSUE THREAD

**Issue by sarajw** [neatnik/omg.lol#636]
### Bug Description

Upon opening Exif data, when one of the fields contains a long string that isn't automatically (like with spaces or hyphens) able to wrap, the table just grows to fit it, and the page zooms out.

Just saw it on my own photo at https://some.pics/6408fa4883fbd

It's pretty minor esp for super beta, but thought worth a bug report in the proper place instead of bothering Adam on discord :)

### Steps to Reproduce

Go to https://some.pics/6408fa4883fbd on a smartphone/emulator and open the Exif data thinger.

**Comment by newbold** [comment]
Thanks! I think I’ve tamed the table now — sorry about that!

**Comment by sarajw** [comment]
Woohoo looks good!
