### ISSUE TITLE
Wattpad Icon Request

### ISSUE THREAD

**Issue by edizbaha** [neatnik/omg.lol#68]
I couldn't find the icon on the font awesome site. Is it possible to add the wattpad icon?

**Comment by newbold** [comment]
Sure, no problem! It's live now. Here's how it looks:

<img width="90" alt="Screen Shot 2021-09-18 at 9 44 34 PM" src="https://user-images.githubusercontent.com/986721/133913046-73b735fe-67ab-4d46-b13b-a91f1a82256c.png">

**Comment by edizbaha** [comment]
@newbold Thanks a lot, but in the dark version of the Minimal theme, the Wattpad icon is black.

**Comment by newbold** [comment]
I am so sorry about that! I inevitably goof something up on these custom icons. Should be fixed now, though!

**Comment by edizbaha** [comment]
> I am so sorry about that! I inevitably goof something up on these custom icons. Should be fixed now, though!

Thank you, solved 🤗
