### ISSUE TITLE
Letterboxd icon support

### ISSUE THREAD

**Issue by stenowtf** [neatnik/omg.lol#70]
I don't know if it is possible, however could the Letterboxd icon be added?

https://letterboxd.com/about/brand/
https://github.com/FortAwesome/Font-Awesome/issues/3680

Many thanks!

**Comment by newbold** [comment]
You got it! Live right now:

<img width="97" alt="Screen Shot 2021-09-23 at 8 17 09 AM" src="https://user-images.githubusercontent.com/986721/134505373-49e6871a-d5d4-4a28-9d4d-3e835f493d44.png">
