### ISSUE TITLE
Revue icon request

### ISSUE THREAD

**Issue by maique** [neatnik/omg.lol#71]
Hey again,

this time around I'm wondering if it's possible to have the Revue (https://www.getrevue.co) icon available? Another one I couldn't find on Font Awesome.

Thanks

**Comment by newbold** [comment]
You got it! This is now live.

<img width="97" alt="Screen Shot 2021-09-27 at 9 51 30 PM" src="https://user-images.githubusercontent.com/986721/135009362-7b4bc5dd-ba3e-4f8a-9dbb-d2a59f851ae4.png">
