### ISSUE TITLE
schema request: podcast

### ISSUE THREAD

**Issue by rjbs** [neatnik/omg.lol#75]
Actually, first, a bogus request:  If you were willing to just say "Look, it's Font Awesome all the way down," you could allow something weird like:

```
item://fa-solid.fa-microphone-alt/[My Podcast](https://pod.cast/)
```

But rather than suggest something this weird:

I would like a way to get fa-microphone-alt (or something) for a podcast link and something for a blog?  I dunno. 👋🏽

**Comment by newbold** [comment]
@andrewcanion, you’re right — the implementation is hard-wired for the "solid" style Font Awesome icons only. Oof! I've just expanded it a little, though, so now if you put an entire Font Awesome class name between the slashes, it’ll pick that up and run with it. E.g. `/fab fa-microblog/`. Sorry for making this so wacky — I really need to find a better way to manage custom icons, but I can at least promise that I’ll always have backwards-compatibility with this current “manual override” process into the future (even though @rjbs above rightly points out the technical debt that I'm incurring, heh).

Also, @rjbs, I’ve finally got schemas in there for both blogs and podcasts at a generic level! These now work:

```
blog://https://example.com
podcast://https://example.com
blog://[My Awesome Blog](https://example.com)
podcast://[My Awesome Podcast](https://example.com)
```

<img width="274" alt="Screen Shot 2021-10-18 at 8 15 45 AM" src="https://user-images.githubusercontent.com/986721/137728643-714e5b63-e428-46a1-a73c-df3e3d1009a4.png">

I'm using [Font Awesome's generic blog icon](https://fontawesome.com/v5.15/icons/blog?style=solid) though I’m honestly not sure about it. I’ve never seen this icon or symbol anywhere in the wild before. I noticed that you’re using a typewriter icon on your own profile, which I actually think is much cooler. Let me know if you think the typewriter should be the global default. :)

**Comment by newbold** [comment]
Typewriter it is!

**Comment by rjbs** [comment]
I mean, easy to say I think my choices are cool, but: I agree, typewriter is way cooler.  Thanks!
