### ISSUE TITLE
Allow address changes

### ISSUE THREAD

**Issue by Vukkyy** [neatnik/omg.lol#93]
I'm not entirely sure how this would work, but it would be pretty cool if you could change your address (say, if I wanted to go from sus.omg.lol to sussy.omg.lol) without having to Contact Support or purchase a new one.

This should probably free up the old address, instead of having it be taken for 10 years.

**Comment by newbold** [comment]
This item is being tracked in the new omg.lol Feedback Forum. To follow its status, visit: https://feedback.omg.lol/16605125815899
